### ISSUE TITLE
Implement Finite State Machine Workflow

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/fsm4j#1]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 24h
Remaining Estimation | ???h

## FSM Workflow in Java/Groovy
- schema and transitions are as Map of Maps (could specified via groovy DSL or just Map of Maps)
- actions: Groovy closures
- conditions: Groovy closures
- object configuration - Map of Maps 
- MachineDefinition 
```
// constructor
MachineDefinition([schema: ...])
// returns map where key is transition and value is a map where key is guard and value is guard evaluation result (true or false) 
def inspectTransitions([from: ..., event: ..., object: ..., request: ..., context: ...])
// returns available transitions
def findAvailableTransitions([from: ..., event: ..., object: ..., request: ..., context: ...])
// returns true or list of Maps where key is condition(guard) and value is result of guard evaluation result (true or false)
def inspectReleaseConditions([from: ..., event: ..., object: ..., request: ..., context: ...])
// list of all states defined in schema
def getAvailableStates()
```
- Machine
```
// history optional, by default it is stored in memory (test purposes)
Machine([machineDefinition: ..., history: ...])
// starts workflow; user and description are optional and used for history
Machine start([object: ..., user: ..., description: ...])
// send event, if event sending files, exception is thrown (this which ones);
// user and description are optional and used for history
Machine sendEvent([object: ..., event: ..., user: ..., description: ...])
// searchParameters - [
//   object: ..., 
//   user: ..., 
//   finishedOn: [
//     gte: ...,  - Date
//     gt: ..., 
//     lt: ..., 
//     lte: ...
//   ]
// ]
// paging - [
//   max: ...,    - example: '25', default value: 100
//   offset: ...  - example: '50', default value: 0
// ] 
// sorting - [
//   by: ...,     - example: 'user', default value: 'finishedOn',
//                  possible values: ['event', 'from', 'to', 
//                                    'user', 'description', 'finishedOn']
//   order: ...   - example: 'asc', default value: 'desc'
// ]
def getHistory(searchParameters, paging, sorting)
// returns a list of available transitions [event, from, to, ...]
def availableTransitions([object])
// gets current state
def currentState([object]) 
// is object in state
def is([object, state]) 
// returns true iff object is in one of final states
def isInFinalState([object]) 
// whether event is available
def can([object, event]) 
// whether event is not available
def cannot([object, event]) 
// weither object can be released from its current state; 'to' is an optional target state
def canBeReleased([object, to, request])
```

Implementation Details
---
The project should be implementing as multi project based on latest Gradle 5.6.x

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/411
See also: https://github.com/OpusCapita/fsm-workflow

**Comment by ddivin-sc** [comment]
Demo available on https://demo.core.dev.opuscapita.com/fsm4j/master/

**Comment by asergeev-sc** [comment]
ToDo:
- add a description/documentation to history plugin
- add more detailed information into the core module on schema (what, why, example), actions, conditions, history

**Comment by ddivin-sc** [comment]
Done.

**Comment by asergeev-sc** [comment]
### FSM Review (java)

#### Core module
- Please, remove type validation, what could be asserted on method call is that something is not passed that is required, but checking for types (Map, List and etc.) is not needed we need clear documentation that basically describe structure. If possible remove ParametersTypeDefinition and Exception classes. It is enough to use simple **assert**-s in places where it is needed see original FSM workflow code.
- Types in constructor/methods 
    - `MachineDefinition(Map params = [:])` could be replaced by `MachineDefinition(params = [:])`
    - `List<Map> inspectConditions(Map params = [:])` could be replaces by `def inspectConditions(params = [:])`
    - etc.
    We don't need to force Map object usage as a parameter, for example people could use Expando or define own classes that are convenient for them. The same is true for returned value we don't need to hardcode ourselves to List of Maps in fact it could be collection or set of other classes.
    What more important is to have good methods descriptions and hell a lot of not tests that test functionality
- MachineDefinition
    - If classLoader is required then it needs to be part (property) of MachineDefinition and have to be passed in constructor, there is no need to pass it to each method. It should have some default value that will be use unless another class loader is configured
    - Method 'inspectConditions' instead of 
```
List result = []
for (int i = 0; i < preparedConditions.size(); i++) {
    boolean isExpression = false
    def condition = preparedConditions[i]
    def res
    if (condition instanceof Closure) {
        res = condition(
                prepareParams(params.conditions[i].params, implicitParams, classLoader)
        ) as Boolean
    } else {
        isExpression = true
        String expression = condition.expression
        res = evaluateExpression(expression, implicitParams, classLoader) as Boolean
    }
    // `negate` property is applied only to function invocations
    result << [condition: params.conditions[i], result: params.conditions[i].negate && !isExpression ? !res : res]
}
```
Use functional approach:
```
preparedConditions.collectEntries {condition ->
  if (condition.expression) {
      return [condition: evaluateExpression(expression, implicitParams)
  } else {
      return [condition: condition.call(prepareParams(params.conditions[i].params, implicitParams))]
  }
}.collect {condition, result ->
    ['condition': condition, condition.negate?(!result):result]
}
```
- Machine
    - the same as for MachineDefinition, use `def` or nothing at all instead of explicit `Map params` or `List` for method return values and passed arguments
- Use java logging (@Log) instead of @Log4j, e.g. dependency to log4j v.1.x could be removed
- We need introduce code coverage like it was done in [original fsm workflow core module](https://github.com/OpusCapita/fsm-workflow/blob/master/packages/core/package.json#L63), so if code is not covered build process should fail

#### History module
- FsmHistoryGrailsPlugin -> FsmWorkflowHistoryGrailsPlugin
- WorkflowTransitionHistoryService - make code translational only inside add/delete methods, don't use readonly transactions
- It loos like 'integration-tests' should be merged (fully?) into history module

#### Editor module
- change package name from '@opuscapita/fsm-workflow-editor' to '@opuscapita/fsm-workflow-jvm-editor' for the moment otherwise we have name clash wi the editor in original JS based repository
#### Build/CI process
- during demo application build there is not need to publish editor package, but    link editor package into demo
- during release process (e.g. whole project is released) editor package should be really published
- define build process for each module in corresponding folder and Makefile should call them one by one.

**Comment by asergeev-sc** [comment]
We need a different name for the whole project, this needs to be discussed.

**Comment by ddivin-sc** [comment]
The project was renamed to **fsm4j**

**Comment by asergeev-sc** [comment]
- Build documentation for Grails plugin at least, also in the case when a new release is published documentation should be deployed to the central storage
- Give a name to build step ```if [ ! -z "$CIRCLE_TAG" ]; then make deploy-release; else make deploy; fi```, so it is clear what it does, like 'test-doc-deploy' or similar
- Test results should be published to CircleCI, also if any other reports, like code coverage, are  available they also should be published to CircleCI

**Comment by ddivin-sc** [comment]
Done.

**Comment by nstoliar-sc** [comment]
1. Work Flow editor does not work in IE.
![24](https://user-images.githubusercontent.com/25082017/75037241-c2fe7280-54c4-11ea-91ed-17c7ee470211.png)

2. Error appears while opening 'History' page on 'Invoice' tab
![25](https://user-images.githubusercontent.com/25082017/75037248-c691f980-54c4-11ea-886b-06c4a89f56f1.png)

**Comment by ddivin-sc** [comment]
Fixed. Please, test it.

**Comment by nstoliar-sc** [comment]
1. Error appears while opening Invoice History in IE and Edge browsers.
![27](https://user-images.githubusercontent.com/25082017/75876677-325e5580-5e27-11ea-9ce6-7f20c9019006.png)
2. Invoice History is not sorted for specific Invoice, all history changes are recorded in common list.
3. Expressions are not resolved while creating new guards.
![28](https://user-images.githubusercontent.com/25082017/75876984-be707d00-5e27-11ea-8886-6957ff591b86.png)
4. "Swap state <deleted state> with a different one" list is closed right away after opening in IE while some state deleting.
![29](https://user-images.githubusercontent.com/25082017/75877421-bf55de80-5e28-11ea-9719-347b26f6a0d6.png)

**Comment by ddivin-sc** [comment]
Were fixed.

**Comment by nstoliar-sc** [comment]
Tested. Workflow editor works correctly. Please, merge with master branch.
